apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-job
  namespace: python-scripts
spec:
  schedule: '*/5 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gdrive-sync
            image: gdrive-aws-sync:latest
            command:
              - /bin/sh
              - "-c"
              - "cat /etc/secret-volume/.env && cat /etc/secret-volume/decisive-fabric-155319-3dcd7ac1c659.json"
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/app"
          restartPolicy: OnFailure
          volumes: 
              - name: secret-volume
                projected:
                    sources: 
                    - secret:
                        name: gdrive-aws-sync-creds
                    - secret:
                        name: gdrive-sa-file
