apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-job
  namespace: python-scripts
spec:
  schedule: '0 0 * * 0'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gdrive-sync
            image: google-aws-sync:1.0
            imagePullPolicy: IfNotPresent
            env:
            - name: SERVICE_ACCOUNT_FILE
              value: "/etc/secrets/decisive-fabric-155319-3dcd7ac1c659.json"
            envFrom:
            - secretRef:
                name: aws-s3-secret  
            volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secrets"
          restartPolicy: OnFailure
          volumes: 
              - name: secret-volume
                projected:
                    sources: 
                    - secret:
                        name: gdrive-aws-sync-creds
                    - secret:
                        name: gdrive-sa-file
