name: Sync Gdrive AWS S3

on:
    workflow_dispatch:

env: # Or as an environment variable
  AccessKey: ${{ secrets.ACCESSKEY }}
  Secretaccesskey: ${{ secrets.SECRETSACCESSKEY }}
  SERVICE_ACCOUNT_FILE:  ${{ secrets.SERVICE_ACCOUNT_FILE }}

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  
      - run: |
          cd /home/runner/work/python-pipelines/gdrive-aws-data-sync-workflow
          pip install -r requirements.txt 

      - name: Inject Secrets to Directory
        uses: mobiledevops/secret-to-file-action@v1
        with: 
          base64-encoded-secret: ${{ secrets.SERVICE_ACCOUNT }}  
          filename: decisive-fabric-155319-3dcd7ac1c659.json
          working-directory: "/home/runner/work/python-pipelines/gdrive-aws-data-sync-workflow"
          # Has to be a better way to do this DRY
      - name: Inject Secrets to Directory
        uses: mobiledevops/secret-to-file-action@v1
        with: 
          base64-encoded-secret: ${{ secrets.ENV }}  
          filename: .env
          working-directory: "/home/runner/work/python-pipelines/gdrive-aws-data-sync-workflow"
      - run: |
          cd /home/runner/work/python-pipelines/gdrive-aws-data-sync-workflow
          python gdrive_sync_to_s3.py


