name: Sync Gdrive AWS S3

on:
    workflow_dispatch:
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository

      - name: Inject Secrets to Directory
        uses: mobiledevops/secret-to-file-action@v1
        with: 
          base64-encoded-secret: ${{ secrets.SERVICE_ACCOUNT }}  
          filename: decisive-fabric-155319-3dcd7ac1c659.json
          working-directory: "."
          # Has to be a better way to do this DRY
      - name: Inject Secrets to Directory
        uses: mobiledevops/secret-to-file-action@v1
        with: 
          base64-encoded-secret: ${{ secrets.ENV }}  
          filename: decisive-fabric-155319-3dcd7ac1c659.json
          working-directory: "."

        uses: actions/checkout@v4
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  
      - run: python gdrive_sync_to_s3.py


